### ISSUE TITLE
I cannot access Appointment attendees through early-bound code

### ISSUE THREAD

**Issue by candelegate** [delegateas/XrmFramework#30] opened 2022-08-08 11:55 UTC
I'm having some issues accessing certain fields on the **Appointment** entity through a plugin using **early-bound code**
 
The plugin is running on **PreOperation Create**, and triggers just fine.

I'm trying to access fields on the **Organizer/RequiredAttendees/OptionalAttendees** fields:
![image](https://user-images.githubusercontent.com/97889500/183410144-77b2b7ad-1090-4189-9c28-8f2c96a94ab6.png)

This is the code I'm running
![image](https://user-images.githubusercontent.com/97889500/183410210-2c7cd84f-2844-4255-b99f-67d7c3525d3d.png)

which calls this method:
![image](https://user-images.githubusercontent.com/97889500/183410434-f1684169-78c4-4cf3-ae56-ece932ccbdbe.png)

Plugin trace:
![image](https://user-images.githubusercontent.com/97889500/183410482-9b6587f3-07f9-447c-b2c2-c74b66eaad51.png)

Based on traces, I can see that the **RequiredAttendees** enumerable does contain the correct number of elements, but whenever I try to iterate through the **RequiredAttendees**, the first element is just null, and I get a **NullReferenceException**.
 

**Using late-bound code:**
![image](https://user-images.githubusercontent.com/97889500/183410737-53144ed5-b434-4c72-a77c-e2d239f3273d.png)

Works perfectly. I can access the **addressused** field and get the correct value.

Plugin trace:
![image](https://user-images.githubusercontent.com/97889500/183411802-a6be6290-cb17-411d-8d63-37120577bd82.png)

**Comment by skovlund** [comment] 2022-08-08 13:41
The issue is with [XrmContext](https://github.com/delegateas/XrmContext). Specifically with `GetEntityCollection<T>` in XrmExtensions.cs which contains an invalid cast by attempting to cast Entity objects to ActivityParty through the `as` keyword instead of using [`ToEntity<ActivityParty>()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entity.toentity), which results in all the elements being converted to null.

**Comment by candelegate** [comment] 2022-08-09 08:00
With the fix, I am getting the following error (taken from plugin trace viewer)

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Type 'IsIT.CRM.D365.Plugins.BusinessDomain.ExtendedEntity`2[IsIT.CRM.D365.Plugins.BusinessDomain.EmptyEnum,IsIT.CRM.D365.Plugins.BusinessDomain.EmptyEnum]' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute.  If the type is a collection, consider marking it with the CollectionDataContractAttribute.  See the Microsoft .NET Framework documentation for other supported types. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040224
Message: Type 'IsIT.CRM.D365.Plugins.BusinessDomain.ExtendedEntity`2[IsIT.CRM.D365.Plugins.BusinessDomain.EmptyEnum,IsIT.CRM.D365.Plugins.BusinessDomain.EmptyEnum]' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute.  If the type is a collection, consider marking it with the CollectionDataContractAttribute.  See the Microsoft .NET Framework documentation for other supported types.
TimeStamp: 2022-08-09T07:10:13.9701338Z
OriginalException: Internal
ExceptionSource: Internal
--
).

**Comment by skovlund** [comment] 2022-08-10 06:56
The above error turned out to be related to passing `List<AcivityParty>` to a Shared Variable. I'm unsure if that should also be supported, but it is not related to this issue, which should still be resolved by the linked fix.

**Closed** 2022-09-13 07:40 UTC
